# Generated by Django 4.0.4 on 2023-04-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_kpi_actuals_actuals_boolean_kpi_actuals_actuals_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_actuals',
            name='perspective_id',
            field=models.ForeignKey(db_column='perspective_id', on_delete=django.db.models.deletion.CASCADE, to='base.scorecard_details'),
        ),
    ]
