# Generated by Django 4.0.4 on 2023-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_kpi_actuals_perspective_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpi_actuals_monthly_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=50)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('target', models.IntegerField()),
                ('jan_actuals', models.IntegerField()),
                ('feb_actuals', models.IntegerField()),
                ('mar_actuals', models.IntegerField()),
                ('apr_actuals', models.IntegerField()),
                ('may_actuals', models.IntegerField()),
                ('jun_actuals', models.IntegerField()),
                ('jul_actuals', models.IntegerField()),
                ('aug_actuals', models.IntegerField()),
                ('sep_actuals', models.IntegerField()),
                ('oct_actuals', models.IntegerField()),
                ('nov_actuals', models.IntegerField()),
                ('dec_actuals', models.IntegerField()),
                ('jan_performance', models.IntegerField()),
                ('jan_score', models.IntegerField()),
                ('feb_performance', models.IntegerField()),
                ('feb_score', models.IntegerField()),
                ('mar_performance', models.IntegerField()),
                ('mar_score', models.IntegerField()),
                ('apr_performance', models.IntegerField()),
                ('apr_score', models.IntegerField()),
                ('may_performance', models.IntegerField()),
                ('may_score', models.IntegerField()),
                ('jun_performance', models.IntegerField()),
                ('jun_score', models.IntegerField()),
                ('jul_performance', models.IntegerField()),
                ('jul_score', models.IntegerField()),
                ('aug_performance', models.IntegerField()),
                ('aug_score', models.IntegerField()),
                ('sep_performance', models.IntegerField()),
                ('sep_score', models.IntegerField()),
                ('oct_performance', models.IntegerField()),
                ('oct_score', models.IntegerField()),
                ('nov_performance', models.IntegerField()),
                ('nov_score', models.IntegerField()),
                ('dec_performance', models.IntegerField()),
                ('dec_score', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('objective_id', models.IntegerField()),
                ('perspective_id', models.IntegerField()),
                ('scorecard_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_kpi_actuals_monthly_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='chart_attributes_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=300)),
                ('attr_key', models.CharField(max_length=300)),
                ('attr_types', models.CharField(max_length=300)),
                ('attr_options', models.CharField(max_length=300)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'tb_sc_chart_attributes_options',
            },
        ),
        migrations.AddField(
            model_name='chart_attributes',
            name='default_attr_value',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart_attributes',
            name='max',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart_attributes',
            name='min',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart_attributes',
            name='user_attr_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
