# Generated by Django 4.0.4 on 2023-05-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_kpi_actuals_monthly_score_chart_attributes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='initiative',
            table='tb_sc_initiative',
        ),
        migrations.CreateModel(
            name='helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('help_context', models.CharField(max_length=500)),
                ('context_order', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
                ('page_no', models.ForeignKey(db_column='page_no', on_delete=django.db.models.deletion.CASCADE, to='base.navigation_menu_details')),
            ],
            options={
                'db_table': 'tb_sc_helper',
            },
        ),
    ]
