# Generated by Django 4.0.4 on 2023-06-06 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_initiative_table_helper'),
    ]

    operations = [
        migrations.CreateModel(
            name='kpi_actuals_monthly_score_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi', models.CharField(max_length=50)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('target', models.IntegerField()),
                ('actuals', models.IntegerField()),
                ('actual_month', models.CharField(max_length=50)),
                ('performance', models.IntegerField()),
                ('score', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('objective_description', models.CharField(max_length=50)),
                ('scorecard_description', models.CharField(max_length=50)),
                ('perspective_description', models.CharField(max_length=50)),
                ('objective_id', models.IntegerField()),
                ('perspective_id', models.IntegerField()),
                ('scorecard_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_kpi_actuals_monthly_score_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vw_kpi_pin_dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_name', models.CharField(max_length=300)),
                ('kpi_score', models.IntegerField()),
                ('target', models.IntegerField()),
                ('curr_actuals', models.IntegerField()),
                ('prev_actuals', models.IntegerField()),
                ('curr_performance', models.IntegerField()),
                ('prev_performance', models.IntegerField()),
                ('curr_score', models.IntegerField()),
                ('prev_score', models.IntegerField()),
                ('objective_id', models.IntegerField()),
                ('perspective_id', models.IntegerField()),
                ('scorecard_id', models.IntegerField()),
                ('kpi_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('pin_flag', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'vw_kpi_pin_dashboard',
            },
        ),
        migrations.CreateModel(
            name='warnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_msg', models.CharField(max_length=500)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_sc_warnings',
            },
        ),
        migrations.RemoveField(
            model_name='helper',
            name='delete_flag',
        ),
        migrations.AddField(
            model_name='kpi_actuals',
            name='summery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='publish_flag',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='kpi_pin_dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kpi_name', models.CharField(max_length=300)),
                ('kpi_score', models.IntegerField()),
                ('pin_flag', models.CharField(default='Y', max_length=1)),
                ('user_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('kpi_id', models.ForeignKey(db_column='kpi_id', on_delete=django.db.models.deletion.CASCADE, to='base.kpi_details')),
            ],
            options={
                'db_table': 'tb_sc_kpi_pin_dashboard',
            },
        ),
    ]
