# Generated by Django 4.0.4 on 2023-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_kpi_actuals_monthly_score_2_vw_kpi_pin_dashboard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kpi_actuals_monthly_score_2',
        ),
        migrations.RemoveField(
            model_name='warnings',
            name='error_type',
        ),
        migrations.AddField(
            model_name='config_codes',
            name='is_active',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='error_category',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='error_code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='error_from',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warnings',
            name='error_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='config_codes',
            name='config_code',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='config_codes',
            name='config_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='config_codes',
            name='config_value',
            field=models.CharField(max_length=500),
        ),
    ]
