# Generated by Django 4.0.4 on 2023-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_delete_kpi_actuals_monthly_score_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_user_access',
            name='kpi_owner',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
