# Generated by Django 4.0.4 on 2023-07-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_license'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='license',
            new_name='user_license',
        ),
        migrations.AlterModelTable(
            name='user_license',
            table='tb_sc_user_license',
        ),
    ]
