# Generated by Django 4.0.4 on 2023-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_license_user_license_alter_user_license_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_license',
            name='delete_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
