# Generated by Django 4.0.4 on 2023-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_pin_chart_to_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config_codes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
