# Generated by Django 4.0.4 on 2023-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
