# Generated by Django 4.0.4 on 2023-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_session_sid_alter_session_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sid',
            field=models.CharField(max_length=455),
        ),
    ]
