# Generated by Django 4.0.4 on 2023-07-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_session_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expired',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='lasttime',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='logintime',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
