# Generated by Django 4.0.4 on 2023-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_notification_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_pending_actions',
            name='action',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
