# Generated by Django 4.0.4 on 2023-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_kpi_pending_actions_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
