# Generated by Django 4.0.4 on 2023-08-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_sso_configure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sso_configure',
            name='username',
        ),
    ]
