# Generated by Django 4.0.4 on 2023-08-28 09:14

import base.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0026_remove_sso_configure_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='query_builder_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'tb_sqb_query_builder_table',
            },
        ),
        migrations.CreateModel(
            name='query_builder_table_columns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_type', models.CharField(max_length=255)),
                ('sort_order', models.IntegerField()),
                ('sort_column', models.CharField(max_length=255)),
                ('group_by', models.CharField(max_length=255, null=True)),
                ('col_function', models.CharField(max_length=255, null=True)),
                ('column_display_order', models.IntegerField()),
                ('column_display_ind', models.CharField(max_length=255, null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'tb_sqb_query_builder_table_columns',
            },
        ),
        migrations.CreateModel(
            name='query_definition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('query_name', models.CharField(max_length=255)),
                ('query_text', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'tb_sqb_query_definition',
            },
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to=base.models.profile_pic_upload_path)),
                ('user_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
                ('temporary_address', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('user_group', models.CharField(max_length=100)),
                ('user_status', models.BooleanField(default=False)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_sc_user_profile',
            },
        ),
        migrations.CreateModel(
            name='query_builder_table_joins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('join_type', models.CharField(max_length=255, null=True)),
                ('join_column_name1', models.CharField(max_length=255, null=True)),
                ('join_column_name2', models.CharField(max_length=255, null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
                ('tab_join_query_id', models.ForeignKey(db_column='tab_join_query_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_definition')),
                ('tab_join_table_id_one', models.ForeignKey(db_column='tab_join_table_id_one', on_delete=django.db.models.deletion.CASCADE, related_name='tab_join_table_one', to='base.query_builder_table')),
                ('tab_join_table_id_two', models.ForeignKey(db_column='tab_join_table_id_two', on_delete=django.db.models.deletion.CASCADE, related_name='tab_join_table_id_two', to='base.query_builder_table')),
            ],
            options={
                'db_table': 'tb_sqb_query_builder_table_joins',
            },
        ),
        migrations.CreateModel(
            name='query_builder_table_groupBy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupbyFunction', models.CharField(max_length=255, null=True)),
                ('having_finter_ind', models.CharField(max_length=1, null=True)),
                ('having_filter_operator', models.CharField(max_length=255, null=True)),
                ('having_filter_value', models.IntegerField(null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
                ('table_grp_column_id', models.ForeignKey(db_column='table_grp_column_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_builder_table_columns')),
                ('table_grp_query_id', models.ForeignKey(db_column='table_grp_query_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_definition')),
                ('table_grp_table_id', models.ForeignKey(db_column='table_grp_table_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_builder_table')),
            ],
            options={
                'db_table': 'tb_sqb_query_builder_table_groupBy',
            },
        ),
        migrations.AddField(
            model_name='query_builder_table_columns',
            name='table_column_query_id',
            field=models.ForeignKey(db_column='table_column_query_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_definition'),
        ),
        migrations.AddField(
            model_name='query_builder_table_columns',
            name='table_column_table_id',
            field=models.ForeignKey(db_column='table_column_table_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_builder_table'),
        ),
        migrations.CreateModel(
            name='query_builder_table_column_filter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=255)),
                ('column_filter', models.CharField(max_length=255)),
                ('column_value', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
                ('tab_filter_query_id', models.ForeignKey(db_column='tab_filter_query_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_definition')),
                ('tab_filter_tale_id', models.ForeignKey(db_column='tab_filter_tale_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_builder_table')),
            ],
            options={
                'db_table': 'tb_sqb_query_builder_table_column_filter',
            },
        ),
        migrations.CreateModel(
            name='query_builder_table_alias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias_name', models.CharField(max_length=255)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
                ('col_alias_query_id', models.ForeignKey(db_column='col_alias_query_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_definition')),
                ('col_alias_table_id', models.ForeignKey(db_column='col_alias_table_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_builder_table')),
            ],
            options={
                'db_table': 'tb_sqb_query_builder_table_alias',
            },
        ),
        migrations.AddField(
            model_name='query_builder_table',
            name='query_id',
            field=models.ForeignKey(db_column='query_id', on_delete=django.db.models.deletion.CASCADE, to='base.query_definition'),
        ),
    ]
