# Generated by Django 4.0.4 on 2023-08-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_query_builder_table_query_builder_table_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_configuration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idle_time', models.IntegerField()),
                ('session_time', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_sc_session_configuration',
            },
        ),
    ]
