# Generated by Django 4.0.4 on 2023-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_session_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_configuration',
            name='created_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session_configuration',
            name='delete_flag',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='session_configuration',
            name='last_updated_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session_configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
