# Generated by Django 4.0.4 on 2023-08-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_session_configuration_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_configuration',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session_configuration',
            name='last_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
