# Generated by Django 4.0.4 on 2023-08-31 14:57

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_session_configuration_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.profile_pic_upload_path),
        ),
    ]
