# Generated by Django 4.0.4 on 2023-09-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_rename_user_name_user_profile_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vw_kpi_pin_dashboard',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='navigation_menu_details',
            name='page_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
