# Generated by Django 4.0.4 on 2023-09-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_vw_kpi_pin_dashboard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
