# Generated by Django 4.0.4 on 2023-10-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_initiative_comments_initiative_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='kpi_dashboard_view',
        ),
        migrations.DeleteModel(
            name='kpi_view',
        ),
        migrations.DeleteModel(
            name='obj_dashboard_view',
        ),
        migrations.DeleteModel(
            name='sc_dashboard_view',
        ),
        migrations.DeleteModel(
            name='sd_dashboard_view',
        ),
        migrations.DeleteModel(
            name='vw_kpi_pin_dashboard',
        ),
    ]
