# Generated by Django 4.0.4 on 2023-11-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_delete_kpi_dashboard_view_delete_kpi_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rb_db_connect_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('connection_name', models.CharField(max_length=255)),
                ('database_type', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('host_id', models.CharField(max_length=20)),
                ('port', models.IntegerField()),
                ('service_name_or_SID', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'rb_tb_sc_db_connect_table',
            },
        ),
    ]
