# Generated by Django 4.0.4 on 2023-11-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_rb_db_connect_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='query_builder_table',
            name='table_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query_builder_table_columns',
            name='column_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='query_definition',
            name='connection_id',
            field=models.ForeignKey(db_column='connection_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='base.rb_db_connect_table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='col_function',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='column_display_ind',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='column_display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='group_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='sort_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='query_builder_table_columns',
            name='sort_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rb_db_connect_table',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
