# Generated by Django 4.0.4 on 2023-11-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_having_finter_ind_query_builder_table_groupby_having_filter_ind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rb_db_connect_table',
            name='database_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rb_db_connect_table',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
