# Generated by Django 4.0.4 on 2023-11-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_rb_db_connect_table_database_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi_details',
            name='actual_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi_details',
            name='file_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kpi_details',
            name='file_path',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
