# Generated by Django 4.0.4 on 2024-03-18 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_kpi_details_actual_type_kpi_details_file_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('iso3', models.CharField(blank=True, max_length=10, null=True)),
                ('iso2', models.CharField(blank=True, max_length=10, null=True)),
                ('numeric_code', models.CharField(blank=True, max_length=10, null=True)),
                ('capital', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('phonecode', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('region_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_sc_countries',
            },
        ),
        migrations.CreateModel(
            name='shared_query_definition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('permission_to', models.CharField(max_length=255)),
                ('permission_by', models.CharField(max_length=255)),
                ('permission_type', models.CharField(max_length=255)),
                ('query_id', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField()),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('delete_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'tb_sqb_shared_query_definition',
            },
        ),
        migrations.RemoveField(
            model_name='kpi_details',
            name='actual_type',
        ),
        migrations.RemoveField(
            model_name='kpi_details',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='kpi_details',
            name='file_path',
        ),
        migrations.AddField(
            model_name='query_builder_table_columns',
            name='alias_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='query_definition',
            name='created_user',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query_definition',
            name='query_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='query_definition',
            name='query_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='query_definition',
            name='query_text',
            field=models.TextField(),
        ),
    ]
