# Generated by Django 4.0.4 on 2024-03-18 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_countries_shared_query_definition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='states',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('iso2', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('country_id', models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='base.countries')),
            ],
            options={
                'db_table': 'tb_sc_states',
            },
        ),
    ]
