# Generated by Django 4.0.4 on 2024-03-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='delete_flag',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='states',
            name='delete_flag',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
