# Generated by Django 4.0.4 on 2024-03-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_countries_delete_flag_states_delete_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_definition',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='org_definition',
            name='country',
        ),
    ]
