# Generated by Django 4.0.4 on 2024-03-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_org_definition_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_definition',
            name='country',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
