# Generated by Django 4.0.4 on 2024-03-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_org_definition_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='currency_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='currency_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='sign',
            field=models.CharField(max_length=5),
        ),
    ]
